// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: categories.sql

package sqlc

import (
	"context"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (parent_id, slug, name_ar, name_en, icon, display_order, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, parent_id, slug, name_ar, name_en, icon, display_order, is_active, created_at, updated_at
`

type CreateCategoryParams struct {
	ParentID     *int64  `json:"parent_id"`
	Slug         string  `json:"slug"`
	NameAr       string  `json:"name_ar"`
	NameEn       *string `json:"name_en"`
	Icon         *string `json:"icon"`
	DisplayOrder int32   `json:"display_order"`
	IsActive     bool    `json:"is_active"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ParentID,
		arg.Slug,
		arg.NameAr,
		arg.NameEn,
		arg.Icon,
		arg.DisplayOrder,
		arg.IsActive,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Slug,
		&i.NameAr,
		&i.NameEn,
		&i.Icon,
		&i.DisplayOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCategoryField = `-- name: CreateCategoryField :one
INSERT INTO category_fields
    (category_id, field_key, label_ar, label_en, field_type, unit, options,
     is_required, is_filterable, display_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, category_id, field_key, label_ar, label_en, field_type, unit, options, is_required, is_filterable, display_order, created_at, updated_at
`

type CreateCategoryFieldParams struct {
	CategoryID   int64     `json:"category_id"`
	FieldKey     string    `json:"field_key"`
	LabelAr      string    `json:"label_ar"`
	LabelEn      *string   `json:"label_en"`
	FieldType    FieldType `json:"field_type"`
	Unit         *string   `json:"unit"`
	Options      []byte    `json:"options"`
	IsRequired   bool      `json:"is_required"`
	IsFilterable bool      `json:"is_filterable"`
	DisplayOrder int32     `json:"display_order"`
}

func (q *Queries) CreateCategoryField(ctx context.Context, arg CreateCategoryFieldParams) (CategoryField, error) {
	row := q.db.QueryRow(ctx, createCategoryField,
		arg.CategoryID,
		arg.FieldKey,
		arg.LabelAr,
		arg.LabelEn,
		arg.FieldType,
		arg.Unit,
		arg.Options,
		arg.IsRequired,
		arg.IsFilterable,
		arg.DisplayOrder,
	)
	var i CategoryField
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.FieldKey,
		&i.LabelAr,
		&i.LabelEn,
		&i.FieldType,
		&i.Unit,
		&i.Options,
		&i.IsRequired,
		&i.IsFilterable,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const deleteCategoryField = `-- name: DeleteCategoryField :exec
DELETE FROM category_fields WHERE id = $1
`

func (q *Queries) DeleteCategoryField(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCategoryField, id)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, parent_id, slug, name_ar, name_en, icon, display_order, is_active, created_at, updated_at FROM categories WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Slug,
		&i.NameAr,
		&i.NameEn,
		&i.Icon,
		&i.DisplayOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, parent_id, slug, name_ar, name_en, icon, display_order, is_active, created_at, updated_at FROM categories WHERE slug = $1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Slug,
		&i.NameAr,
		&i.NameEn,
		&i.Icon,
		&i.DisplayOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllCategories = `-- name: ListAllCategories :many
SELECT id, parent_id, slug, name_ar, name_en, icon, display_order, is_active, created_at, updated_at FROM categories
ORDER BY display_order, name_ar
`

func (q *Queries) ListAllCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listAllCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Slug,
			&i.NameAr,
			&i.NameEn,
			&i.Icon,
			&i.DisplayOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, parent_id, slug, name_ar, name_en, icon, display_order, is_active, created_at, updated_at FROM categories
WHERE is_active = true
ORDER BY display_order, name_ar
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Slug,
			&i.NameAr,
			&i.NameEn,
			&i.Icon,
			&i.DisplayOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFieldsByCategory = `-- name: ListFieldsByCategory :many
SELECT id, category_id, field_key, label_ar, label_en, field_type, unit, options, is_required, is_filterable, display_order, created_at, updated_at FROM category_fields
WHERE category_id = $1
ORDER BY display_order
`

func (q *Queries) ListFieldsByCategory(ctx context.Context, categoryID int64) ([]CategoryField, error) {
	rows, err := q.db.Query(ctx, listFieldsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryField
	for rows.Next() {
		var i CategoryField
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.FieldKey,
			&i.LabelAr,
			&i.LabelEn,
			&i.FieldType,
			&i.Unit,
			&i.Options,
			&i.IsRequired,
			&i.IsFilterable,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResolvedFieldsForCategory = `-- name: ListResolvedFieldsForCategory :many
WITH RECURSIVE chain(id, parent_id) AS (
    SELECT c.id, c.parent_id FROM categories c WHERE c.id = $1
    UNION ALL
    SELECT c.id, c.parent_id FROM categories c
    JOIN chain ch ON c.id = ch.parent_id
)
SELECT f.id, f.category_id, f.field_key, f.label_ar, f.label_en, f.field_type, f.unit, f.options, f.is_required, f.is_filterable, f.display_order, f.created_at, f.updated_at FROM category_fields f
JOIN chain ch ON f.category_id = ch.id
ORDER BY f.display_order
`

// Resolve fields for a category AND all its ancestors (inherited attributes).
func (q *Queries) ListResolvedFieldsForCategory(ctx context.Context, id int64) ([]CategoryField, error) {
	rows, err := q.db.Query(ctx, listResolvedFieldsForCategory, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryField
	for rows.Next() {
		var i CategoryField
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.FieldKey,
			&i.LabelAr,
			&i.LabelEn,
			&i.FieldType,
			&i.Unit,
			&i.Options,
			&i.IsRequired,
			&i.IsFilterable,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET parent_id = $2, slug = $3, name_ar = $4, name_en = $5, icon = $6,
    display_order = $7, is_active = $8
WHERE id = $1
RETURNING id, parent_id, slug, name_ar, name_en, icon, display_order, is_active, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID           int64   `json:"id"`
	ParentID     *int64  `json:"parent_id"`
	Slug         string  `json:"slug"`
	NameAr       string  `json:"name_ar"`
	NameEn       *string `json:"name_en"`
	Icon         *string `json:"icon"`
	DisplayOrder int32   `json:"display_order"`
	IsActive     bool    `json:"is_active"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.ParentID,
		arg.Slug,
		arg.NameAr,
		arg.NameEn,
		arg.Icon,
		arg.DisplayOrder,
		arg.IsActive,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Slug,
		&i.NameAr,
		&i.NameEn,
		&i.Icon,
		&i.DisplayOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
