// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: contact.sql

package sqlc

import (
	"context"
)

const countContactMessages = `-- name: CountContactMessages :one
SELECT count(*) FROM contact_messages
`

func (q *Queries) CountContactMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countContactMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadContactMessages = `-- name: CountUnreadContactMessages :one
SELECT count(*) FROM contact_messages WHERE is_read = false
`

func (q *Queries) CountUnreadContactMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadContactMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContactMessage = `-- name: CreateContactMessage :one
INSERT INTO contact_messages (name, phone, email, message)
VALUES ($1, $2, $3, $4)
RETURNING id, name, phone, email, message, is_read, created_at
`

type CreateContactMessageParams struct {
	Name    string  `json:"name"`
	Phone   *string `json:"phone"`
	Email   *string `json:"email"`
	Message string  `json:"message"`
}

func (q *Queries) CreateContactMessage(ctx context.Context, arg CreateContactMessageParams) (ContactMessage, error) {
	row := q.db.QueryRow(ctx, createContactMessage,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Message,
	)
	var i ContactMessage
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Message,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContactMessage = `-- name: DeleteContactMessage :exec
DELETE FROM contact_messages WHERE id = $1
`

func (q *Queries) DeleteContactMessage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteContactMessage, id)
	return err
}

const listContactMessages = `-- name: ListContactMessages :many
SELECT id, name, phone, email, message, is_read, created_at FROM contact_messages
ORDER BY is_read, created_at DESC
LIMIT $2 OFFSET $1
`

type ListContactMessagesParams struct {
	Off int32 `json:"off"`
	Lim int32 `json:"lim"`
}

func (q *Queries) ListContactMessages(ctx context.Context, arg ListContactMessagesParams) ([]ContactMessage, error) {
	rows, err := q.db.Query(ctx, listContactMessages, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContactMessage
	for rows.Next() {
		var i ContactMessage
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Message,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markContactMessageRead = `-- name: MarkContactMessageRead :exec
UPDATE contact_messages SET is_read = true WHERE id = $1
`

func (q *Queries) MarkContactMessageRead(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markContactMessageRead, id)
	return err
}
