// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: favorites.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO favorites (user_id, listing_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddFavoriteParams struct {
	UserID    int64 `json:"user_id"`
	ListingID int64 `json:"listing_id"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.ListingID)
	return err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (listing_id, reporter_user_id, reason, details)
VALUES ($1, $2, $3, $4)
RETURNING id, listing_id, reporter_user_id, reason, details, status, created_at, reviewed_at, reviewed_by
`

type CreateReportParams struct {
	ListingID      int64   `json:"listing_id"`
	ReporterUserID *int64  `json:"reporter_user_id"`
	Reason         string  `json:"reason"`
	Details        *string `json:"details"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ListingID,
		arg.ReporterUserID,
		arg.Reason,
		arg.Details,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.ReporterUserID,
		&i.Reason,
		&i.Details,
		&i.Status,
		&i.CreatedAt,
		&i.ReviewedAt,
		&i.ReviewedBy,
	)
	return i, err
}

const isFavorite = `-- name: IsFavorite :one
SELECT EXISTS (
    SELECT 1 FROM favorites WHERE user_id = $1 AND listing_id = $2
)
`

type IsFavoriteParams struct {
	UserID    int64 `json:"user_id"`
	ListingID int64 `json:"listing_id"`
}

func (q *Queries) IsFavorite(ctx context.Context, arg IsFavoriteParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFavorite, arg.UserID, arg.ListingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFavoritesByUser = `-- name: ListFavoritesByUser :many
SELECT l.id, l.user_id, l.category_id, l.location_id, l.title, l.slug, l.description, l.price, l.currency, l.price_type, l.contact_phone, l.whatsapp_number, l.status, l.is_featured, l.featured_until, l.views_count, l.published_at, l.expires_at, l.created_at, l.updated_at, l.deleted_at, COALESCE(pi.storage_key, '') AS primary_image
FROM favorites fv
JOIN listings l ON l.id = fv.listing_id
LEFT JOIN LATERAL (
    SELECT storage_key FROM listing_images i
    WHERE i.listing_id = l.id ORDER BY i.is_primary DESC, i.display_order LIMIT 1
) pi ON true
WHERE fv.user_id = $1 AND l.deleted_at IS NULL
ORDER BY fv.created_at DESC
`

type ListFavoritesByUserRow struct {
	ID             int64          `json:"id"`
	UserID         int64          `json:"user_id"`
	CategoryID     int64          `json:"category_id"`
	LocationID     *int64         `json:"location_id"`
	Title          string         `json:"title"`
	Slug           *string        `json:"slug"`
	Description    string         `json:"description"`
	Price          pgtype.Numeric `json:"price"`
	Currency       string         `json:"currency"`
	PriceType      PriceType      `json:"price_type"`
	ContactPhone   *string        `json:"contact_phone"`
	WhatsappNumber *string        `json:"whatsapp_number"`
	Status         ListingStatus  `json:"status"`
	IsFeatured     bool           `json:"is_featured"`
	FeaturedUntil  *time.Time     `json:"featured_until"`
	ViewsCount     int64          `json:"views_count"`
	PublishedAt    *time.Time     `json:"published_at"`
	ExpiresAt      *time.Time     `json:"expires_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	DeletedAt      *time.Time     `json:"deleted_at"`
	PrimaryImage   string         `json:"primary_image"`
}

func (q *Queries) ListFavoritesByUser(ctx context.Context, userID int64) ([]ListFavoritesByUserRow, error) {
	rows, err := q.db.Query(ctx, listFavoritesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavoritesByUserRow
	for rows.Next() {
		var i ListFavoritesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.LocationID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.Currency,
			&i.PriceType,
			&i.ContactPhone,
			&i.WhatsappNumber,
			&i.Status,
			&i.IsFeatured,
			&i.FeaturedUntil,
			&i.ViewsCount,
			&i.PublishedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PrimaryImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorites WHERE user_id = $1 AND listing_id = $2
`

type RemoveFavoriteParams struct {
	UserID    int64 `json:"user_id"`
	ListingID int64 `json:"listing_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.ListingID)
	return err
}
