// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: listings.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addListingImage = `-- name: AddListingImage :one
INSERT INTO listing_images (listing_id, storage_key, alt_text, is_primary, display_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, listing_id, storage_key, alt_text, is_primary, display_order, created_at
`

type AddListingImageParams struct {
	ListingID    int64   `json:"listing_id"`
	StorageKey   string  `json:"storage_key"`
	AltText      *string `json:"alt_text"`
	IsPrimary    bool    `json:"is_primary"`
	DisplayOrder int32   `json:"display_order"`
}

// ---- images ----
func (q *Queries) AddListingImage(ctx context.Context, arg AddListingImageParams) (ListingImage, error) {
	row := q.db.QueryRow(ctx, addListingImage,
		arg.ListingID,
		arg.StorageKey,
		arg.AltText,
		arg.IsPrimary,
		arg.DisplayOrder,
	)
	var i ListingImage
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.StorageKey,
		&i.AltText,
		&i.IsPrimary,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const adminListListings = `-- name: AdminListListings :many
SELECT l.id, l.user_id, l.category_id, l.location_id, l.title, l.slug, l.description, l.price, l.currency, l.price_type, l.contact_phone, l.whatsapp_number, l.status, l.is_featured, l.featured_until, l.views_count, l.published_at, l.expires_at, l.created_at, l.updated_at, l.deleted_at, COALESCE(pi.storage_key, '') AS primary_image,
       c.name_ar AS category_name_ar
FROM listings l
JOIN categories c ON c.id = l.category_id
LEFT JOIN LATERAL (
    SELECT storage_key FROM listing_images i
    WHERE i.listing_id = l.id ORDER BY i.is_primary DESC, i.display_order LIMIT 1
) pi ON true
WHERE l.deleted_at IS NULL
  AND ($1::listing_status IS NULL OR l.status = $1)
ORDER BY l.created_at DESC
LIMIT 100
`

type AdminListListingsRow struct {
	ID             int64          `json:"id"`
	UserID         int64          `json:"user_id"`
	CategoryID     int64          `json:"category_id"`
	LocationID     *int64         `json:"location_id"`
	Title          string         `json:"title"`
	Slug           *string        `json:"slug"`
	Description    string         `json:"description"`
	Price          pgtype.Numeric `json:"price"`
	Currency       string         `json:"currency"`
	PriceType      PriceType      `json:"price_type"`
	ContactPhone   *string        `json:"contact_phone"`
	WhatsappNumber *string        `json:"whatsapp_number"`
	Status         ListingStatus  `json:"status"`
	IsFeatured     bool           `json:"is_featured"`
	FeaturedUntil  *time.Time     `json:"featured_until"`
	ViewsCount     int64          `json:"views_count"`
	PublishedAt    *time.Time     `json:"published_at"`
	ExpiresAt      *time.Time     `json:"expires_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	DeletedAt      *time.Time     `json:"deleted_at"`
	PrimaryImage   string         `json:"primary_image"`
	CategoryNameAr string         `json:"category_name_ar"`
}

func (q *Queries) AdminListListings(ctx context.Context, status NullListingStatus) ([]AdminListListingsRow, error) {
	rows, err := q.db.Query(ctx, adminListListings, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminListListingsRow
	for rows.Next() {
		var i AdminListListingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.LocationID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.Currency,
			&i.PriceType,
			&i.ContactPhone,
			&i.WhatsappNumber,
			&i.Status,
			&i.IsFeatured,
			&i.FeaturedUntil,
			&i.ViewsCount,
			&i.PublishedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PrimaryImage,
			&i.CategoryNameAr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countListings = `-- name: CountListings :one
SELECT count(*) FROM listings l
WHERE l.deleted_at IS NULL
  AND l.status = 'active'
  AND ($1::bigint IS NULL OR l.category_id = $1)
  AND ($2::bigint IS NULL OR l.location_id = $2)
  AND ($3::numeric IS NULL OR l.price >= $3)
  AND ($4::numeric IS NULL OR l.price <= $4)
  AND ($5::text IS NULL
       OR l.title ILIKE '%' || $5 || '%'
       OR l.description ILIKE '%' || $5 || '%')
`

type CountListingsParams struct {
	CategoryID *int64         `json:"category_id"`
	LocationID *int64         `json:"location_id"`
	MinPrice   pgtype.Numeric `json:"min_price"`
	MaxPrice   pgtype.Numeric `json:"max_price"`
	Keyword    *string        `json:"keyword"`
}

func (q *Queries) CountListings(ctx context.Context, arg CountListingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countListings,
		arg.CategoryID,
		arg.LocationID,
		arg.MinPrice,
		arg.MaxPrice,
		arg.Keyword,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createListing = `-- name: CreateListing :one
INSERT INTO listings
    (user_id, category_id, location_id, title, slug, description, price, currency,
     price_type, contact_phone, whatsapp_number, status, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, user_id, category_id, location_id, title, slug, description, price, currency, price_type, contact_phone, whatsapp_number, status, is_featured, featured_until, views_count, published_at, expires_at, created_at, updated_at, deleted_at
`

type CreateListingParams struct {
	UserID         int64          `json:"user_id"`
	CategoryID     int64          `json:"category_id"`
	LocationID     *int64         `json:"location_id"`
	Title          string         `json:"title"`
	Slug           *string        `json:"slug"`
	Description    string         `json:"description"`
	Price          pgtype.Numeric `json:"price"`
	Currency       string         `json:"currency"`
	PriceType      PriceType      `json:"price_type"`
	ContactPhone   *string        `json:"contact_phone"`
	WhatsappNumber *string        `json:"whatsapp_number"`
	Status         ListingStatus  `json:"status"`
	ExpiresAt      *time.Time     `json:"expires_at"`
}

func (q *Queries) CreateListing(ctx context.Context, arg CreateListingParams) (Listing, error) {
	row := q.db.QueryRow(ctx, createListing,
		arg.UserID,
		arg.CategoryID,
		arg.LocationID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Price,
		arg.Currency,
		arg.PriceType,
		arg.ContactPhone,
		arg.WhatsappNumber,
		arg.Status,
		arg.ExpiresAt,
	)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.LocationID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.PriceType,
		&i.ContactPhone,
		&i.WhatsappNumber,
		&i.Status,
		&i.IsFeatured,
		&i.FeaturedUntil,
		&i.ViewsCount,
		&i.PublishedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAttributesByListing = `-- name: DeleteAttributesByListing :exec
DELETE FROM listing_attributes WHERE listing_id = $1
`

func (q *Queries) DeleteAttributesByListing(ctx context.Context, listingID int64) error {
	_, err := q.db.Exec(ctx, deleteAttributesByListing, listingID)
	return err
}

const deleteListingImage = `-- name: DeleteListingImage :exec
DELETE FROM listing_images WHERE id = $1
`

func (q *Queries) DeleteListingImage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteListingImage, id)
	return err
}

const getListingByID = `-- name: GetListingByID :one
SELECT l.id, l.user_id, l.category_id, l.location_id, l.title, l.slug, l.description, l.price, l.currency, l.price_type, l.contact_phone, l.whatsapp_number, l.status, l.is_featured, l.featured_until, l.views_count, l.published_at, l.expires_at, l.created_at, l.updated_at, l.deleted_at,
       c.slug AS category_slug, c.name_ar AS category_name_ar, c.name_en AS category_name_en,
       loc.name_ar AS location_name_ar, loc.name_en AS location_name_en
FROM listings l
JOIN categories c ON c.id = l.category_id
LEFT JOIN locations loc ON loc.id = l.location_id
WHERE l.id = $1 AND l.deleted_at IS NULL
`

type GetListingByIDRow struct {
	Listing        Listing `json:"listing"`
	CategorySlug   string  `json:"category_slug"`
	CategoryNameAr string  `json:"category_name_ar"`
	CategoryNameEn *string `json:"category_name_en"`
	LocationNameAr *string `json:"location_name_ar"`
	LocationNameEn *string `json:"location_name_en"`
}

func (q *Queries) GetListingByID(ctx context.Context, id int64) (GetListingByIDRow, error) {
	row := q.db.QueryRow(ctx, getListingByID, id)
	var i GetListingByIDRow
	err := row.Scan(
		&i.Listing.ID,
		&i.Listing.UserID,
		&i.Listing.CategoryID,
		&i.Listing.LocationID,
		&i.Listing.Title,
		&i.Listing.Slug,
		&i.Listing.Description,
		&i.Listing.Price,
		&i.Listing.Currency,
		&i.Listing.PriceType,
		&i.Listing.ContactPhone,
		&i.Listing.WhatsappNumber,
		&i.Listing.Status,
		&i.Listing.IsFeatured,
		&i.Listing.FeaturedUntil,
		&i.Listing.ViewsCount,
		&i.Listing.PublishedAt,
		&i.Listing.ExpiresAt,
		&i.Listing.CreatedAt,
		&i.Listing.UpdatedAt,
		&i.Listing.DeletedAt,
		&i.CategorySlug,
		&i.CategoryNameAr,
		&i.CategoryNameEn,
		&i.LocationNameAr,
		&i.LocationNameEn,
	)
	return i, err
}

const getListingImage = `-- name: GetListingImage :one
SELECT id, listing_id, storage_key, alt_text, is_primary, display_order, created_at FROM listing_images WHERE id = $1
`

func (q *Queries) GetListingImage(ctx context.Context, id int64) (ListingImage, error) {
	row := q.db.QueryRow(ctx, getListingImage, id)
	var i ListingImage
	err := row.Scan(
		&i.ID,
		&i.ListingID,
		&i.StorageKey,
		&i.AltText,
		&i.IsPrimary,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const incrementListingViews = `-- name: IncrementListingViews :exec
UPDATE listings SET views_count = views_count + 1 WHERE id = $1
`

func (q *Queries) IncrementListingViews(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementListingViews, id)
	return err
}

const listAttributesByListing = `-- name: ListAttributesByListing :many
SELECT a.id, a.listing_id, a.field_id, a.value_text, a.value_number, a.value_boolean, a.value_date, a.value_json, f.field_key, f.label_ar, f.label_en, f.field_type, f.unit, f.options
FROM listing_attributes a
JOIN category_fields f ON f.id = a.field_id
WHERE a.listing_id = $1
ORDER BY f.display_order
`

type ListAttributesByListingRow struct {
	ID           int64          `json:"id"`
	ListingID    int64          `json:"listing_id"`
	FieldID      int64          `json:"field_id"`
	ValueText    *string        `json:"value_text"`
	ValueNumber  pgtype.Numeric `json:"value_number"`
	ValueBoolean *bool          `json:"value_boolean"`
	ValueDate    pgtype.Date    `json:"value_date"`
	ValueJson    []byte         `json:"value_json"`
	FieldKey     string         `json:"field_key"`
	LabelAr      string         `json:"label_ar"`
	LabelEn      *string        `json:"label_en"`
	FieldType    FieldType      `json:"field_type"`
	Unit         *string        `json:"unit"`
	Options      []byte         `json:"options"`
}

func (q *Queries) ListAttributesByListing(ctx context.Context, listingID int64) ([]ListAttributesByListingRow, error) {
	rows, err := q.db.Query(ctx, listAttributesByListing, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttributesByListingRow
	for rows.Next() {
		var i ListAttributesByListingRow
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.FieldID,
			&i.ValueText,
			&i.ValueNumber,
			&i.ValueBoolean,
			&i.ValueDate,
			&i.ValueJson,
			&i.FieldKey,
			&i.LabelAr,
			&i.LabelEn,
			&i.FieldType,
			&i.Unit,
			&i.Options,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImagesByListing = `-- name: ListImagesByListing :many
SELECT id, listing_id, storage_key, alt_text, is_primary, display_order, created_at FROM listing_images
WHERE listing_id = $1
ORDER BY is_primary DESC, display_order
`

func (q *Queries) ListImagesByListing(ctx context.Context, listingID int64) ([]ListingImage, error) {
	rows, err := q.db.Query(ctx, listImagesByListing, listingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListingImage
	for rows.Next() {
		var i ListingImage
		if err := rows.Scan(
			&i.ID,
			&i.ListingID,
			&i.StorageKey,
			&i.AltText,
			&i.IsPrimary,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListingsByUser = `-- name: ListListingsByUser :many
SELECT l.id, l.user_id, l.category_id, l.location_id, l.title, l.slug, l.description, l.price, l.currency, l.price_type, l.contact_phone, l.whatsapp_number, l.status, l.is_featured, l.featured_until, l.views_count, l.published_at, l.expires_at, l.created_at, l.updated_at, l.deleted_at, COALESCE(pi.storage_key, '') AS primary_image
FROM listings l
LEFT JOIN LATERAL (
    SELECT storage_key FROM listing_images i
    WHERE i.listing_id = l.id ORDER BY i.is_primary DESC, i.display_order LIMIT 1
) pi ON true
WHERE l.user_id = $1 AND l.deleted_at IS NULL
ORDER BY l.created_at DESC
`

type ListListingsByUserRow struct {
	ID             int64          `json:"id"`
	UserID         int64          `json:"user_id"`
	CategoryID     int64          `json:"category_id"`
	LocationID     *int64         `json:"location_id"`
	Title          string         `json:"title"`
	Slug           *string        `json:"slug"`
	Description    string         `json:"description"`
	Price          pgtype.Numeric `json:"price"`
	Currency       string         `json:"currency"`
	PriceType      PriceType      `json:"price_type"`
	ContactPhone   *string        `json:"contact_phone"`
	WhatsappNumber *string        `json:"whatsapp_number"`
	Status         ListingStatus  `json:"status"`
	IsFeatured     bool           `json:"is_featured"`
	FeaturedUntil  *time.Time     `json:"featured_until"`
	ViewsCount     int64          `json:"views_count"`
	PublishedAt    *time.Time     `json:"published_at"`
	ExpiresAt      *time.Time     `json:"expires_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	DeletedAt      *time.Time     `json:"deleted_at"`
	PrimaryImage   string         `json:"primary_image"`
}

func (q *Queries) ListListingsByUser(ctx context.Context, userID int64) ([]ListListingsByUserRow, error) {
	rows, err := q.db.Query(ctx, listListingsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListListingsByUserRow
	for rows.Next() {
		var i ListListingsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.LocationID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.Currency,
			&i.PriceType,
			&i.ContactPhone,
			&i.WhatsappNumber,
			&i.Status,
			&i.IsFeatured,
			&i.FeaturedUntil,
			&i.ViewsCount,
			&i.PublishedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.PrimaryImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchListings = `-- name: SearchListings :many
SELECT l.id, l.user_id, l.category_id, l.location_id, l.title, l.slug, l.description, l.price, l.currency, l.price_type, l.contact_phone, l.whatsapp_number, l.status, l.is_featured, l.featured_until, l.views_count, l.published_at, l.expires_at, l.created_at, l.updated_at, l.deleted_at,
       c.slug AS category_slug, c.name_ar AS category_name_ar,
       loc.name_ar AS location_name_ar,
       COALESCE(pi.storage_key, '') AS primary_image
FROM listings l
JOIN categories c ON c.id = l.category_id
LEFT JOIN locations loc ON loc.id = l.location_id
LEFT JOIN LATERAL (
    SELECT storage_key FROM listing_images i
    WHERE i.listing_id = l.id ORDER BY i.is_primary DESC, i.display_order LIMIT 1
) pi ON true
WHERE l.deleted_at IS NULL
  AND l.status = 'active'
  AND ($1::bigint IS NULL OR l.category_id = $1)
  AND ($2::bigint IS NULL OR l.location_id = $2)
  AND ($3::numeric IS NULL OR l.price >= $3)
  AND ($4::numeric IS NULL OR l.price <= $4)
  AND ($5::text IS NULL
       OR l.title ILIKE '%' || $5 || '%'
       OR l.description ILIKE '%' || $5 || '%')
ORDER BY l.is_featured DESC, l.published_at DESC NULLS LAST, l.created_at DESC
LIMIT $7 OFFSET $6
`

type SearchListingsParams struct {
	CategoryID *int64         `json:"category_id"`
	LocationID *int64         `json:"location_id"`
	MinPrice   pgtype.Numeric `json:"min_price"`
	MaxPrice   pgtype.Numeric `json:"max_price"`
	Keyword    *string        `json:"keyword"`
	Off        int32          `json:"off"`
	Lim        int32          `json:"lim"`
}

type SearchListingsRow struct {
	ID             int64          `json:"id"`
	UserID         int64          `json:"user_id"`
	CategoryID     int64          `json:"category_id"`
	LocationID     *int64         `json:"location_id"`
	Title          string         `json:"title"`
	Slug           *string        `json:"slug"`
	Description    string         `json:"description"`
	Price          pgtype.Numeric `json:"price"`
	Currency       string         `json:"currency"`
	PriceType      PriceType      `json:"price_type"`
	ContactPhone   *string        `json:"contact_phone"`
	WhatsappNumber *string        `json:"whatsapp_number"`
	Status         ListingStatus  `json:"status"`
	IsFeatured     bool           `json:"is_featured"`
	FeaturedUntil  *time.Time     `json:"featured_until"`
	ViewsCount     int64          `json:"views_count"`
	PublishedAt    *time.Time     `json:"published_at"`
	ExpiresAt      *time.Time     `json:"expires_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	DeletedAt      *time.Time     `json:"deleted_at"`
	CategorySlug   string         `json:"category_slug"`
	CategoryNameAr string         `json:"category_name_ar"`
	LocationNameAr *string        `json:"location_name_ar"`
	PrimaryImage   string         `json:"primary_image"`
}

func (q *Queries) SearchListings(ctx context.Context, arg SearchListingsParams) ([]SearchListingsRow, error) {
	rows, err := q.db.Query(ctx, searchListings,
		arg.CategoryID,
		arg.LocationID,
		arg.MinPrice,
		arg.MaxPrice,
		arg.Keyword,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchListingsRow
	for rows.Next() {
		var i SearchListingsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.LocationID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Price,
			&i.Currency,
			&i.PriceType,
			&i.ContactPhone,
			&i.WhatsappNumber,
			&i.Status,
			&i.IsFeatured,
			&i.FeaturedUntil,
			&i.ViewsCount,
			&i.PublishedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CategorySlug,
			&i.CategoryNameAr,
			&i.LocationNameAr,
			&i.PrimaryImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteListing = `-- name: SoftDeleteListing :exec
UPDATE listings SET deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteListing(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteListing, id)
	return err
}

const updateListing = `-- name: UpdateListing :one
UPDATE listings
SET category_id = $2, location_id = $3, title = $4, slug = $5, description = $6,
    price = $7, price_type = $8, contact_phone = $9, whatsapp_number = $10
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, category_id, location_id, title, slug, description, price, currency, price_type, contact_phone, whatsapp_number, status, is_featured, featured_until, views_count, published_at, expires_at, created_at, updated_at, deleted_at
`

type UpdateListingParams struct {
	ID             int64          `json:"id"`
	CategoryID     int64          `json:"category_id"`
	LocationID     *int64         `json:"location_id"`
	Title          string         `json:"title"`
	Slug           *string        `json:"slug"`
	Description    string         `json:"description"`
	Price          pgtype.Numeric `json:"price"`
	PriceType      PriceType      `json:"price_type"`
	ContactPhone   *string        `json:"contact_phone"`
	WhatsappNumber *string        `json:"whatsapp_number"`
}

func (q *Queries) UpdateListing(ctx context.Context, arg UpdateListingParams) (Listing, error) {
	row := q.db.QueryRow(ctx, updateListing,
		arg.ID,
		arg.CategoryID,
		arg.LocationID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Price,
		arg.PriceType,
		arg.ContactPhone,
		arg.WhatsappNumber,
	)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.LocationID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.PriceType,
		&i.ContactPhone,
		&i.WhatsappNumber,
		&i.Status,
		&i.IsFeatured,
		&i.FeaturedUntil,
		&i.ViewsCount,
		&i.PublishedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateListingStatus = `-- name: UpdateListingStatus :one
UPDATE listings
SET status = $2,
    published_at = CASE WHEN $2 = 'active'::listing_status AND published_at IS NULL THEN now() ELSE published_at END
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, category_id, location_id, title, slug, description, price, currency, price_type, contact_phone, whatsapp_number, status, is_featured, featured_until, views_count, published_at, expires_at, created_at, updated_at, deleted_at
`

type UpdateListingStatusParams struct {
	ID     int64         `json:"id"`
	Status ListingStatus `json:"status"`
}

func (q *Queries) UpdateListingStatus(ctx context.Context, arg UpdateListingStatusParams) (Listing, error) {
	row := q.db.QueryRow(ctx, updateListingStatus, arg.ID, arg.Status)
	var i Listing
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.LocationID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Price,
		&i.Currency,
		&i.PriceType,
		&i.ContactPhone,
		&i.WhatsappNumber,
		&i.Status,
		&i.IsFeatured,
		&i.FeaturedUntil,
		&i.ViewsCount,
		&i.PublishedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertListingAttribute = `-- name: UpsertListingAttribute :exec
INSERT INTO listing_attributes
    (listing_id, field_id, value_text, value_number, value_boolean, value_date, value_json)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (listing_id, field_id) DO UPDATE
SET value_text = EXCLUDED.value_text,
    value_number = EXCLUDED.value_number,
    value_boolean = EXCLUDED.value_boolean,
    value_date = EXCLUDED.value_date,
    value_json = EXCLUDED.value_json
`

type UpsertListingAttributeParams struct {
	ListingID    int64          `json:"listing_id"`
	FieldID      int64          `json:"field_id"`
	ValueText    *string        `json:"value_text"`
	ValueNumber  pgtype.Numeric `json:"value_number"`
	ValueBoolean *bool          `json:"value_boolean"`
	ValueDate    pgtype.Date    `json:"value_date"`
	ValueJson    []byte         `json:"value_json"`
}

// ---- attributes (EAV) ----
func (q *Queries) UpsertListingAttribute(ctx context.Context, arg UpsertListingAttributeParams) error {
	_, err := q.db.Exec(ctx, upsertListingAttribute,
		arg.ListingID,
		arg.FieldID,
		arg.ValueText,
		arg.ValueNumber,
		arg.ValueBoolean,
		arg.ValueDate,
		arg.ValueJson,
	)
	return err
}
