// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: locations.sql

package sqlc

import (
	"context"
)

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, parent_id, type, name_ar, name_en, slug, created_at FROM locations WHERE id = $1
`

func (q *Queries) GetLocationByID(ctx context.Context, id int64) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Type,
		&i.NameAr,
		&i.NameEn,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const listGovernorates = `-- name: ListGovernorates :many
SELECT id, parent_id, type, name_ar, name_en, slug, created_at FROM locations
WHERE type = 'governorate'
ORDER BY name_ar
`

func (q *Queries) ListGovernorates(ctx context.Context) ([]Location, error) {
	rows, err := q.db.Query(ctx, listGovernorates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Type,
			&i.NameAr,
			&i.NameEn,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many
SELECT id, parent_id, type, name_ar, name_en, slug, created_at FROM locations
ORDER BY type, name_ar
`

func (q *Queries) ListLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.Query(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Type,
			&i.NameAr,
			&i.NameEn,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWilayatsByGovernorate = `-- name: ListWilayatsByGovernorate :many
SELECT id, parent_id, type, name_ar, name_en, slug, created_at FROM locations
WHERE parent_id = $1
ORDER BY name_ar
`

func (q *Queries) ListWilayatsByGovernorate(ctx context.Context, parentID *int64) ([]Location, error) {
	rows, err := q.db.Query(ctx, listWilayatsByGovernorate, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Type,
			&i.NameAr,
			&i.NameEn,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
