// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type FieldType string

const (
	FieldTypeText        FieldType = "text"
	FieldTypeTextarea    FieldType = "textarea"
	FieldTypeNumber      FieldType = "number"
	FieldTypeSelect      FieldType = "select"
	FieldTypeMultiselect FieldType = "multiselect"
	FieldTypeBoolean     FieldType = "boolean"
	FieldTypeDate        FieldType = "date"
	FieldTypeUrl         FieldType = "url"
)

func (e *FieldType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FieldType(s)
	case string:
		*e = FieldType(s)
	default:
		return fmt.Errorf("unsupported scan type for FieldType: %T", src)
	}
	return nil
}

type NullFieldType struct {
	FieldType FieldType `json:"field_type"`
	Valid     bool      `json:"valid"` // Valid is true if FieldType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFieldType) Scan(value interface{}) error {
	if value == nil {
		ns.FieldType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FieldType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFieldType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FieldType), nil
}

func (e FieldType) Valid() bool {
	switch e {
	case FieldTypeText,
		FieldTypeTextarea,
		FieldTypeNumber,
		FieldTypeSelect,
		FieldTypeMultiselect,
		FieldTypeBoolean,
		FieldTypeDate,
		FieldTypeUrl:
		return true
	}
	return false
}

func AllFieldTypeValues() []FieldType {
	return []FieldType{
		FieldTypeText,
		FieldTypeTextarea,
		FieldTypeNumber,
		FieldTypeSelect,
		FieldTypeMultiselect,
		FieldTypeBoolean,
		FieldTypeDate,
		FieldTypeUrl,
	}
}

type ListingStatus string

const (
	ListingStatusDraft    ListingStatus = "draft"
	ListingStatusPending  ListingStatus = "pending"
	ListingStatusActive   ListingStatus = "active"
	ListingStatusSold     ListingStatus = "sold"
	ListingStatusExpired  ListingStatus = "expired"
	ListingStatusRejected ListingStatus = "rejected"
)

func (e *ListingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ListingStatus(s)
	case string:
		*e = ListingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ListingStatus: %T", src)
	}
	return nil
}

type NullListingStatus struct {
	ListingStatus ListingStatus `json:"listing_status"`
	Valid         bool          `json:"valid"` // Valid is true if ListingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullListingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ListingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ListingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullListingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ListingStatus), nil
}

func (e ListingStatus) Valid() bool {
	switch e {
	case ListingStatusDraft,
		ListingStatusPending,
		ListingStatusActive,
		ListingStatusSold,
		ListingStatusExpired,
		ListingStatusRejected:
		return true
	}
	return false
}

func AllListingStatusValues() []ListingStatus {
	return []ListingStatus{
		ListingStatusDraft,
		ListingStatusPending,
		ListingStatusActive,
		ListingStatusSold,
		ListingStatusExpired,
		ListingStatusRejected,
	}
}

type LocationType string

const (
	LocationTypeGovernorate LocationType = "governorate"
	LocationTypeWilayat     LocationType = "wilayat"
)

func (e *LocationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LocationType(s)
	case string:
		*e = LocationType(s)
	default:
		return fmt.Errorf("unsupported scan type for LocationType: %T", src)
	}
	return nil
}

type NullLocationType struct {
	LocationType LocationType `json:"location_type"`
	Valid        bool         `json:"valid"` // Valid is true if LocationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLocationType) Scan(value interface{}) error {
	if value == nil {
		ns.LocationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LocationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLocationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LocationType), nil
}

func (e LocationType) Valid() bool {
	switch e {
	case LocationTypeGovernorate,
		LocationTypeWilayat:
		return true
	}
	return false
}

func AllLocationTypeValues() []LocationType {
	return []LocationType{
		LocationTypeGovernorate,
		LocationTypeWilayat,
	}
}

type PriceType string

const (
	PriceTypeFixed      PriceType = "fixed"
	PriceTypeNegotiable PriceType = "negotiable"
	PriceTypeOnRequest  PriceType = "on_request"
)

func (e *PriceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PriceType(s)
	case string:
		*e = PriceType(s)
	default:
		return fmt.Errorf("unsupported scan type for PriceType: %T", src)
	}
	return nil
}

type NullPriceType struct {
	PriceType PriceType `json:"price_type"`
	Valid     bool      `json:"valid"` // Valid is true if PriceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPriceType) Scan(value interface{}) error {
	if value == nil {
		ns.PriceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PriceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPriceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PriceType), nil
}

func (e PriceType) Valid() bool {
	switch e {
	case PriceTypeFixed,
		PriceTypeNegotiable,
		PriceTypeOnRequest:
		return true
	}
	return false
}

func AllPriceTypeValues() []PriceType {
	return []PriceType{
		PriceTypeFixed,
		PriceTypeNegotiable,
		PriceTypeOnRequest,
	}
}

type ReportStatus string

const (
	ReportStatusOpen      ReportStatus = "open"
	ReportStatusReviewed  ReportStatus = "reviewed"
	ReportStatusDismissed ReportStatus = "dismissed"
)

func (e *ReportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportStatus(s)
	case string:
		*e = ReportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportStatus: %T", src)
	}
	return nil
}

type NullReportStatus struct {
	ReportStatus ReportStatus `json:"report_status"`
	Valid        bool         `json:"valid"` // Valid is true if ReportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportStatus), nil
}

func (e ReportStatus) Valid() bool {
	switch e {
	case ReportStatusOpen,
		ReportStatusReviewed,
		ReportStatusDismissed:
		return true
	}
	return false
}

func AllReportStatusValues() []ReportStatus {
	return []ReportStatus{
		ReportStatusOpen,
		ReportStatusReviewed,
		ReportStatusDismissed,
	}
}

type UserRole string

const (
	UserRoleUser  UserRole = "user"
	UserRoleAdmin UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

func (e UserRole) Valid() bool {
	switch e {
	case UserRoleUser,
		UserRoleAdmin:
		return true
	}
	return false
}

func AllUserRoleValues() []UserRole {
	return []UserRole{
		UserRoleUser,
		UserRoleAdmin,
	}
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
	UserStatusDeleted   UserStatus = "deleted"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

func (e UserStatus) Valid() bool {
	switch e {
	case UserStatusActive,
		UserStatusSuspended,
		UserStatusDeleted:
		return true
	}
	return false
}

func AllUserStatusValues() []UserStatus {
	return []UserStatus{
		UserStatusActive,
		UserStatusSuspended,
		UserStatusDeleted,
	}
}

type AuthProvider struct {
	ID             int64     `json:"id"`
	UserID         int64     `json:"user_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type Category struct {
	ID           int64     `json:"id"`
	ParentID     *int64    `json:"parent_id"`
	Slug         string    `json:"slug"`
	NameAr       string    `json:"name_ar"`
	NameEn       *string   `json:"name_en"`
	Icon         *string   `json:"icon"`
	DisplayOrder int32     `json:"display_order"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type CategoryField struct {
	ID           int64     `json:"id"`
	CategoryID   int64     `json:"category_id"`
	FieldKey     string    `json:"field_key"`
	LabelAr      string    `json:"label_ar"`
	LabelEn      *string   `json:"label_en"`
	FieldType    FieldType `json:"field_type"`
	Unit         *string   `json:"unit"`
	Options      []byte    `json:"options"`
	IsRequired   bool      `json:"is_required"`
	IsFilterable bool      `json:"is_filterable"`
	DisplayOrder int32     `json:"display_order"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type Favorite struct {
	UserID    int64     `json:"user_id"`
	ListingID int64     `json:"listing_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Listing struct {
	ID             int64          `json:"id"`
	UserID         int64          `json:"user_id"`
	CategoryID     int64          `json:"category_id"`
	LocationID     *int64         `json:"location_id"`
	Title          string         `json:"title"`
	Slug           *string        `json:"slug"`
	Description    string         `json:"description"`
	Price          pgtype.Numeric `json:"price"`
	Currency       string         `json:"currency"`
	PriceType      PriceType      `json:"price_type"`
	ContactPhone   *string        `json:"contact_phone"`
	WhatsappNumber *string        `json:"whatsapp_number"`
	Status         ListingStatus  `json:"status"`
	IsFeatured     bool           `json:"is_featured"`
	FeaturedUntil  *time.Time     `json:"featured_until"`
	ViewsCount     int64          `json:"views_count"`
	PublishedAt    *time.Time     `json:"published_at"`
	ExpiresAt      *time.Time     `json:"expires_at"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	DeletedAt      *time.Time     `json:"deleted_at"`
}

type ListingAttribute struct {
	ID           int64          `json:"id"`
	ListingID    int64          `json:"listing_id"`
	FieldID      int64          `json:"field_id"`
	ValueText    *string        `json:"value_text"`
	ValueNumber  pgtype.Numeric `json:"value_number"`
	ValueBoolean *bool          `json:"value_boolean"`
	ValueDate    pgtype.Date    `json:"value_date"`
	ValueJson    []byte         `json:"value_json"`
}

type ListingImage struct {
	ID           int64     `json:"id"`
	ListingID    int64     `json:"listing_id"`
	StorageKey   string    `json:"storage_key"`
	AltText      *string   `json:"alt_text"`
	IsPrimary    bool      `json:"is_primary"`
	DisplayOrder int32     `json:"display_order"`
	CreatedAt    time.Time `json:"created_at"`
}

type Location struct {
	ID        int64        `json:"id"`
	ParentID  *int64       `json:"parent_id"`
	Type      LocationType `json:"type"`
	NameAr    string       `json:"name_ar"`
	NameEn    *string      `json:"name_en"`
	Slug      string       `json:"slug"`
	CreatedAt time.Time    `json:"created_at"`
}

type Report struct {
	ID             int64        `json:"id"`
	ListingID      int64        `json:"listing_id"`
	ReporterUserID *int64       `json:"reporter_user_id"`
	Reason         string       `json:"reason"`
	Details        *string      `json:"details"`
	Status         ReportStatus `json:"status"`
	CreatedAt      time.Time    `json:"created_at"`
	ReviewedAt     *time.Time   `json:"reviewed_at"`
	ReviewedBy     *int64       `json:"reviewed_by"`
}

type Session struct {
	ID               int64       `json:"id"`
	UserID           int64       `json:"user_id"`
	RefreshTokenHash string      `json:"refresh_token_hash"`
	UserAgent        *string     `json:"user_agent"`
	IpAddress        *netip.Addr `json:"ip_address"`
	ExpiresAt        time.Time   `json:"expires_at"`
	RevokedAt        *time.Time  `json:"revoked_at"`
	CreatedAt        time.Time   `json:"created_at"`
}

type User struct {
	ID              int64      `json:"id"`
	Email           string     `json:"email"`
	Username        *string    `json:"username"`
	PasswordHash    *string    `json:"password_hash"`
	FullName        string     `json:"full_name"`
	Phone           *string    `json:"phone"`
	WhatsappNumber  *string    `json:"whatsapp_number"`
	Role            UserRole   `json:"role"`
	Status          UserStatus `json:"status"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}
