// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: payments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (user_id, listing_id, purpose, amount, currency, provider)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, listing_id, purpose, amount, currency, status, provider, provider_ref, provider_payload, paid_at, created_at, updated_at
`

type CreatePaymentParams struct {
	UserID    int64          `json:"user_id"`
	ListingID *int64         `json:"listing_id"`
	Purpose   string         `json:"purpose"`
	Amount    pgtype.Numeric `json:"amount"`
	Currency  string         `json:"currency"`
	Provider  string         `json:"provider"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.ListingID,
		arg.Purpose,
		arg.Amount,
		arg.Currency,
		arg.Provider,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ListingID,
		&i.Purpose,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderRef,
		&i.ProviderPayload,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, user_id, listing_id, purpose, amount, currency, status, provider, provider_ref, provider_payload, paid_at, created_at, updated_at FROM payments WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ListingID,
		&i.Purpose,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderRef,
		&i.ProviderPayload,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByProviderRef = `-- name: GetPaymentByProviderRef :one
SELECT id, user_id, listing_id, purpose, amount, currency, status, provider, provider_ref, provider_payload, paid_at, created_at, updated_at FROM payments WHERE provider_ref = $1
`

func (q *Queries) GetPaymentByProviderRef(ctx context.Context, providerRef *string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByProviderRef, providerRef)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ListingID,
		&i.Purpose,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderRef,
		&i.ProviderPayload,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentsByUser = `-- name: ListPaymentsByUser :many
SELECT id, user_id, listing_id, purpose, amount, currency, status, provider, provider_ref, provider_payload, paid_at, created_at, updated_at FROM payments
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPaymentsByUser(ctx context.Context, userID int64) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ListingID,
			&i.Purpose,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.Provider,
			&i.ProviderRef,
			&i.ProviderPayload,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentFailed = `-- name: MarkPaymentFailed :exec
UPDATE payments
SET status = 'failed', provider_payload = COALESCE($2, provider_payload)
WHERE id = $1 AND status = 'pending'
`

type MarkPaymentFailedParams struct {
	ID              int64  `json:"id"`
	ProviderPayload []byte `json:"provider_payload"`
}

func (q *Queries) MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) error {
	_, err := q.db.Exec(ctx, markPaymentFailed, arg.ID, arg.ProviderPayload)
	return err
}

const markPaymentPaid = `-- name: MarkPaymentPaid :one
UPDATE payments
SET status = 'paid', paid_at = now(), provider_payload = COALESCE($2, provider_payload)
WHERE id = $1 AND status = 'pending'
RETURNING id, user_id, listing_id, purpose, amount, currency, status, provider, provider_ref, provider_payload, paid_at, created_at, updated_at
`

type MarkPaymentPaidParams struct {
	ID              int64  `json:"id"`
	ProviderPayload []byte `json:"provider_payload"`
}

// Idempotent: only a still-pending payment transitions to paid.
func (q *Queries) MarkPaymentPaid(ctx context.Context, arg MarkPaymentPaidParams) (Payment, error) {
	row := q.db.QueryRow(ctx, markPaymentPaid, arg.ID, arg.ProviderPayload)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ListingID,
		&i.Purpose,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderRef,
		&i.ProviderPayload,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPaymentCheckout = `-- name: SetPaymentCheckout :one
UPDATE payments
SET provider_ref = $2, provider_payload = $3
WHERE id = $1
RETURNING id, user_id, listing_id, purpose, amount, currency, status, provider, provider_ref, provider_payload, paid_at, created_at, updated_at
`

type SetPaymentCheckoutParams struct {
	ID              int64   `json:"id"`
	ProviderRef     *string `json:"provider_ref"`
	ProviderPayload []byte  `json:"provider_payload"`
}

// Records the gateway session/checkout id after a checkout is created.
func (q *Queries) SetPaymentCheckout(ctx context.Context, arg SetPaymentCheckoutParams) (Payment, error) {
	row := q.db.QueryRow(ctx, setPaymentCheckout, arg.ID, arg.ProviderRef, arg.ProviderPayload)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ListingID,
		&i.Purpose,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderRef,
		&i.ProviderPayload,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
