// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, password_hash, full_name, phone, whatsapp_number)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, username, password_hash, full_name, phone, whatsapp_number, role, status, email_verified_at, created_at, updated_at
`

type CreateUserParams struct {
	Email          string  `json:"email"`
	Username       *string `json:"username"`
	PasswordHash   *string `json:"password_hash"`
	FullName       string  `json:"full_name"`
	Phone          *string `json:"phone"`
	WhatsappNumber *string `json:"whatsapp_number"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.FullName,
		arg.Phone,
		arg.WhatsappNumber,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.WhatsappNumber,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password_hash, full_name, phone, whatsapp_number, role, status, email_verified_at, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.WhatsappNumber,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, password_hash, full_name, phone, whatsapp_number, role, status, email_verified_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.WhatsappNumber,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password_hash, full_name, phone, whatsapp_number, role, status, email_verified_at, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.WhatsappNumber,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET full_name = $2, phone = $3, whatsapp_number = $4
WHERE id = $1
RETURNING id, email, username, password_hash, full_name, phone, whatsapp_number, role, status, email_verified_at, created_at, updated_at
`

type UpdateUserProfileParams struct {
	ID             int64   `json:"id"`
	FullName       string  `json:"full_name"`
	Phone          *string `json:"phone"`
	WhatsappNumber *string `json:"whatsapp_number"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.FullName,
		arg.Phone,
		arg.WhatsappNumber,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.WhatsappNumber,
		&i.Role,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
